# Generated by Django 3.2.20 on 2024-08-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
