# Generated by Django 3.2.20 on 2024-08-13 10:40

from django.db import migrations, models
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=reservations.models.Restaurant, max_length=100),
        ),
    ]
