# Generated by Django 3.2.20 on 2024-08-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.restaurant'),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'reservation_time')},
        ),
    ]
