# Generated by Django 3.2.20 on 2024-08-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_table_table_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='table_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.restaurant'),
        ),
    ]
