# Generated by Django 3.2.20 on 2024-08-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20240814_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_number',
        ),
    ]
