# Generated by Django 3.2.20 on 2024-08-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_rename_number_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
