# Generated by Django 3.2.20 on 2024-08-15 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_remove_reservation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
