# Generated by Django 3.2.20 on 2024-08-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_auto_20240815_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slot',
        ),
    ]
