# Generated by Django 3.2.20 on 2024-08-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_remove_reservation_time_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_time',
            new_name='reservation_datetime',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('table', 'reservation_datetime')},
        ),
    ]
