# Generated by Django 3.2.20 on 2024-08-15 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_auto_20240815_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
